spring:
  application:
    name: humanaid-backend
  
  # 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  
  # SQL 초기화 설정
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  
  # H2 콘솔 활성화 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # 메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /api

# 로깅 설정
logging:
  level:
    com.humanaid: DEBUG
    org.springframework.security: DEBUG

# JWT 설정
jwt:
  secret: ${JWT_SECRET:humanaid-secret-key-for-jwt-token-generation-2024}
  expiration: 86400000 # 24시간

# CORS 설정
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:8080
    - https://humanaid.digital

# 파일 업로드 설정
spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 10MB

---
# 프로덕션 환경 설정
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/humanaid_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:humanaid_user}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  h2:
    console:
      enabled: false